export const opcodes = [
  {
    opcode: '00',
    name: 'STOP',
    gas: '0',
    input: '',
    output: '',
    description: 'Halts execution',
    group: 'Stop & Arithmetic',
    note: '',
  },
  {
    opcode: '01',
    name: 'ADD',
    gas: '3',
    input: 'a | b',
    output: 'a + b',
    description: 'Addition operation',
    group: 'Stop & Arithmetic',
    note: '',
  },
  {
    opcode: '02',
    name: 'CALLDATACOPY',
    gas: '200',
    input: 'a | b',
    output: 'a * b',
    description: 'Multiplication operation',
    group: 'Stop & Arithmetic',
    note: '',
  },
  {
    opcode: '08',
    name: 'ADDMOD',
    gas: '10',
    input: 'a | b | N',
    output: '(a + b) % N',
    description: 'Multiplication operation',
    group: 'Stack & Memory',
    note: 'All intermediate calculations of this operation are not subject to the 2**256 modulo',
  },
]
