import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>EVM Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black h-screen flex justify-center items-center">
        <h1 className="text-center text-white">EVM Codes</h1>
      </main>
    </div>
  )
}

export default Home
