import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'

import Footer from './Footer'
import Nav from './Nav'

const HomeLayout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>EVM Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script src="/ethereum.min.js" strategy="beforeInteractive" />

      <div className="flex flex-col h-screen justify-between">
        <Nav />

        <main className="mb-auto mt-60">{children}</main>

        <Footer />
      </div>
    </>
  )
}

export default HomeLayout
