import type { NextPage } from 'next'
import Head from 'next/head'

import Container from '../Container'
import Footer from './Footer'
import Nav from './Nav'

const HomeLayout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>EVM Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col h-screen justify-between">
        <Nav />

        <main className="mb-auto flex h-screen items-center">
          <Container>{children}</Container>
        </main>

        <Footer />
      </div>
    </>
  )
}

export default HomeLayout
